### ISSUE TITLE
Hội chẩn - XML5

### ISSUE THREAD

**Issue by le-an-87** [oth-dhghospital/dhg.hospitaladmin#1]
XML 5 (Admin): Bệnh nhân có 2 biên bản hội chẩn trong cùng 1 diễn biến. 
+ XML 5 (Admin): hội chẩn chưa load đúng theo ngày y lệnh của qtdieutri.
+ XML 5 (Admin) chưa load được kết luận của lần hội chẩn thứ 2!
Thông tin dữ liệu:
- tên data: testcovid_dktpct
- Mã bệnh án: 000001
- Tháng 1/2022
![image](https://user-images.githubusercontent.com/96155021/148519902-221225b8-867b-4336-b671-120124228917.png)
![image](https://user-images.githubusercontent.com/96155021/148520188-0c8070df-2e5e-4ba7-91d8-b6d73f788d91.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Thử lại bản mới giúp anh nhé @le-an-87 https://github.com/oth-dhghospital/dhg.hospitaladmin/commit/4f85579ee5c7556d068ae0a77d29212444541fa1

**Comment by le-an-87** [comment]
ok được rồi anh ơi!
