### ISSUE TITLE
Danh mục nhân viên nghỉ việc.

### ISSUE THREAD

**Issue by lqbinh1987** [oth-dhghospital/dhg.hospitaladmin#11]
Danh mục nhân viên có 2 tab Nghỉ việc và Đang làm việc nhưng khi mở lần đầu mở form lên mặc định nó load tất cả luôn, phải nhán mút mũi tên cho nó chuyển qua tab Nghỉ việc rồi nhấn lên cái tab Nghỉ việc cái nữa mới lọc ra được, tương tự muốn chuyển qua tab Đang làm việc thì phải nhấn mũi tên để nó chuyển qua rồi phải nhấn chuột lên tab đó cái nữa mới lọc được ds đó.>
Yêu cầu: 
- Lần đầu mở form lên thì lọc theo tab đang hiển thị.
- Hiển thị đầy đủ 2 tab, không cần nhấn nút mũi tên để chuyển và nhấn thêm lần nữa.

Data: dbphoidt

![image](https://user-images.githubusercontent.com/99630883/169994784-35f9ff95-7a43-4c1f-a47f-fc8b8f5a90d6.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại đây https://github.com/oth-dhghospital/dhg.hospitaladmin/commit/b152dd377fa9e08ed09d5974fb1b0a0777c5a355
