### ISSUE TITLE
Lỗi: Load danh mục VTYT khi cấu hình Thuốc/VTYT cho cls trong danh mục cls

### ISSUE THREAD

**Issue by le-an-87** [oth-dhghospital/dhg.hospitaladmin#15]
- Chức năng tìm kiếm không tìm được các thuốc chưa nhập.
- Khi tìm kiếm rồi thì không còn hiển thị các thuốc chưa nhập.
- VTYT đã xóa thuộc kho 13 vẫn hiển thị trong danh sách.
- Tên data: an_medichsg_tonkhohc
Khi vào chọn thuốc thì load đủ danh mục
![image](https://user-images.githubusercontent.com/96155021/173717321-94950ee4-3438-47fb-b2c6-a7b2a0dd711d.png)
chức năng tìm kiếm không thấy được các thuốc không có nhập kho
![image](https://user-images.githubusercontent.com/96155021/173717389-d456db98-2130-406a-bc67-d148c06d71af.png)
sau khi tìm kiếm xong không hiển thị đủ danh mục thuốc
![image](https://user-images.githubusercontent.com/96155021/173717502-3ebc7c4b-f9a3-4c80-8f6e-0f194a8b062d.png)
Danh mục hiển thị luôn thuốc đã xóa như mã hàng B20
![image](https://user-images.githubusercontent.com/96155021/173717582-2fbd011f-f2a4-4aeb-9cc8-77fc17d7e8af.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
- Cập nhật tại https://github.com/oth-dhghospital/dhg.hospitaladmin/commit/fcff7ee2a5cd3557ad1ef1d23dc98a79cb810998
