### ISSUE TITLE
XML5 tên cls có ký tự đặt biệt < khi gửi lên cổng bhxh báo lỗi không giải mã được xml

### ISSUE THREAD

**Issue by le-an-87** [oth-dhghospital/dhg.hospitaladmin#2]
Bệnh nhân có chỉ định cls có tên chứa ký tự đặt biệt < khi gửi lên cổng báo lỗi không giải mã được xml
Tên data: an_quangngai_xml5
mã bệnh nhân: 2022008882
![image](https://user-images.githubusercontent.com/96155021/155641525-6de3e865-5fa3-4e08-ad92-14a12d9c2caa.png)

file xml (xóa đuôi .docx trước khi xem)
[51014_2022_02_2022008882_2202004993_20220220_xml5.xml.docx](https://github.com/oth-dhghospital/dhg.hospitaladmin/files/8137934/51014_2022_02_2022008882_2202004993_20220220_xml5.xml.docx)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại đây 52ee06a0995676b15c4521cd44dad2d31b91012b
