### ISSUE TITLE
Lỗi hạn thẻ tạm - vẫn còn sai so với mô tả mới

### ISSUE THREAD

**Issue by lqbinh1987** [oth-dhghospital/dhg.hospitaladmin#3]
Đã cấu hình Lấy ngày ra viện làm ngày kết thúc hạn thẻ, nhưng khi xuất xml trên admin và gửi tự động vẫn còn lấy theo giá trị nhập hạn thẻ trên form, trong hình có 2 BN, 1 cas trong mà thẻ có "KT" thì nó lấy đúng hạn thẻ theo ngày xuất viện, nhưng cas còn lại không có "KT" (theo mô tả mới thì không có băt cái này) nhưng nó vẫn ko lấy hạn thẻ theo ngày ra viện.
Data: dbnhidong_thetam, 2 BN của khoa mã 05.
 
![image](https://user-images.githubusercontent.com/99630883/165010209-ded04379-2ffc-4a62-99d2-eaeaca362ae5.png)
![image](https://user-images.githubusercontent.com/99630883/165010036-e62a711f-a197-4302-b688-394a45c3aaaf.png)

**Comment by lqbinh1987** [comment]
Nhờ a Hậu coi cái này, BV đang gửi bị sai nhiều.

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại đây 52ee06a0995676b15c4521cd44dad2d31b91012b
