### ISSUE TITLE
Admin-Printer XML và bảng kê load sai thành tiền và tiền bệnh nhân tự trả khi chỉnh mã nhóm thủ thuật 18

### ISSUE THREAD

**Issue by BlueTea92** [oth-dhghospital/dhg.hospitaladmin#4]
![image](https://user-images.githubusercontent.com/97272332/161473989-c39c3297-9ad9-4fcc-bbb3-b8fe215fafd8.png)
![image](https://user-images.githubusercontent.com/97272332/161483960-f92f3b9a-1054-4940-9f3b-b5475c0aa2c9.png)

- Cập nhật mã 2348 loại CLS thủ thuật qua nhóm 18. 
- chỉ định CLS thủ thuật chỉnh tỉ lệ thanh toán thành 80%
- > XML không tính lại cột thành tiền và có thêm tiền bệnh nhân tự trả
- > bảng kê 01 xếp CLS nhóm 18 vào nhóm dịch vụ khác và tính sai thành tiền và bệnh nhân tự trả
+ data máy chủ: tra_dangthuytram_reports_saithanhtien
+ https://drive.google.com/file/d/1dwVZ8ZbVU1ptARSki1c35uiejqz0XMwt/view?usp=sharing

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại đây 52ee06a0995676b15c4521cd44dad2d31b91012b
