### ISSUE TITLE
Hô trợ thao tác danh mục CLS TT37

### ISSUE THREAD

**Issue by lqbinh1987** [oth-dhghospital/dhg.hospitaladmin#6]
Bổ sung thêm cột **ma_nhom_cv2348** trong chức năng cập bằng file excel để người dùng cập nhật mã nhóm cho nhanh, hiện tại nhều BV than cập nhật lâu quá vì chuyển nhiều thủ thuật qua nhóm mới.
Data: dbtimmach_angiang_tt78

![image](https://user-images.githubusercontent.com/99630883/164592751-0106047a-24e1-44e9-885c-08b6af2847cf.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại đây https://github.com/oth-dhghospital/dhg.hospitaladmin/commit/aaa7abab22c8723198d33abff6ad6385f2ff6cc1
