### ISSUE TITLE
Admin tạo giường bệnh mới 4210 báo lỗi

### ISSUE THREAD

**Issue by le-an-87** [oth-dhghospital/dhg.hospitaladmin#9]
Admin khi tạo giường bệnh mới 4210 báo lỗi
tên data test: an_lapvo_full_17042022
![image](https://user-images.githubusercontent.com/96155021/167763145-6d3bf710-d9cc-41cf-9064-17b7cba3afe2.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Do lỗi trường tự động oid của postgres nên không sử dụng được chức năng này.

**Comment by le-an-87** [comment]
ok anh
